### ISSUE TITLE
The memory consumption is almost constant

### ISSUE THREAD

**Issue by DaShenZi721** [ayaka14732/jax-smi#2]
Hi, thanks for offering this repo! 
I have recently been testing the memory usage of several baselines for text tasks on the Long-Range Arena benchmark. However, I have found that regardless of which baseline I use or the batch size, the memory usage displayed by the 'jax-smi' command is almost the same, as shown in the figure below. 
![image](https://user-images.githubusercontent.com/39253334/227682094-e527b92c-cd1e-44ed-b8be-e3348d43df16.png)

The code can be found:
[https://github.com/google-research/long-range-arena/blob/main/lra_benchmarks/text_classification/train.py](https://github.com/google-research/long-range-arena/blob/main/lra_benchmarks/text_classification/train.py)

I added the following two lines of code in the main function according to the README.
```
from jax_smi import initialise_tracking
initialise_tracking()
```

My jax environment is as follows
```
python 3.8.16
jax 0.2.16
jax-lib 0.1.67+cuda111
flax 0.3.0
tensorflow 2.11.0
```

**Comment by ayaka14732** [comment]
This is true. If you use jit, the memory consumption would be almost constant

**Comment by DaShenZi721** [comment]
I think you might have misunderstood me. What I meant to say was that regardless of the baseline or batch size used, the total memory consumption is around 160MB.

**Comment by ayaka14732** [comment]
I am sorry for my previous mistake. This is an interesting observation. I think we can create a discussion in https://github.com/google/jax/discussions

**Comment by DaShenZi721** [comment]
Sure. Maybe it's not a problem with jax-smi, but with jax itself.

**Comment by DaShenZi721** [comment]
Thank you for your reply!
